# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= key_input
GAME_TITLE	:= Key input example

# Source code paths

SOURCEDIRS	:= source

include ../../tests/Makefile.include
