# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= exit_to_loader
GAME_TITLE	:= Exit to loader test

# Source code paths

SOURCEDIRS	:= source

include ../../Makefile.include
