# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= exit_to_loader
GAME_TITLE	:= Exit to loader test

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
