# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Michele Di Giorgio, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= maxmod_audio_modes
GAME_TITLE	:= Audio modes
GAME_SUBTITLE	:= Maxmod

# Source code paths

AUDIODIRS	:= audio

# Libraries

LIBS		:= -lnds9 -lmm9
LIBDIRS		:= $(BLOCKSDS)/libs/maxmod

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
