# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= periph_maths_coprocessor
GAME_TITLE	:= Maths Coprocessor
GAME_SUBTITLE	:= Peripherals

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
