# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dldi_arm7_arm9
GAME_TITLE	:= DLDI ARM7 or ARM9 test

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
