# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= dldi_arm7_arm9
GAME_TITLE	:= DLDI ARM7 or ARM9 test

# Source code paths

SOURCEDIRS	:= source

include ../../Makefile.include
