# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024-2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= bg_scroll_big_bmp
GAME_TITLE	:= Scroll big bitmap
GAME_SUBTITLE	:= 2D graphics: BGs

# Source code paths
# -----------------

GFXDIRS		:= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
