# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= data_cache_ops
GAME_TITLE	:= Data cache ops test

# Source code paths

SOURCEDIRS	:= source

include ../Makefile.include
