# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_fs_utime
GAME_TITLE	:= SD utime() example
GAME_SUBTITLE	:= Tests: Filesystem

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
