# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Michele Di Giorgio, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= maxmod_song_event
GAME_TITLE	:= Audio song event
GAME_SUBTITLE	:= Maxmod

# Source code paths

AUDIODIRS	:= audio
GFXDIRS		:= graphics

# Libraries

LIBS		:= -lnds9 -lmm9
LIBDIRS		:= $(BLOCKSDS)/libs/maxmod

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
