# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_periph_slot2_extram
GAME_TITLE	:= Slot-2 external RAM test
GAME_SUBTITLE	:= Tests: Peripherals

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
