# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_ipc_fifo_full
GAME_TITLE	:= FIFO full test
GAME_SUBTITLE	:= Tests: IPC

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
