# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_fs_label
GAME_TITLE	:= FAT label API example
GAME_SUBTITLE	:= Tests: Filesystem

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
