# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= console_arm7_console
GAME_TITLE	:= ARM7 Console
GAME_SUBTITLE	:= Console

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
