# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= assert_test
GAME_TITLE	:= Assert test

# Source code paths

SOURCEDIRS	:= source
LIBS		:= -lnds9d

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
