# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= hw_math
GAME_TITLE	:= Hardware Math routines

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
