# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= time_timers
GAME_TITLE	:= Timers
GAME_SUBTITLE	:= Time

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
