# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= filesystem_scandir
GAME_TITLE	:= SD scandir() example

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
