# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= input_touch_pressure
GAME_TITLE	:= Touch pressure example
GAME_SUBTITLE	:= Input

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
