# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= exception_handler
GAME_TITLE	:= Exception handler test

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
