# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# Use debug build of libnds

LIBS		:= -lnds9d

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile.arm9
