# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= debug_exception_handler
GAME_TITLE	:= Exception handler test
GAME_SUBTITLE	:= Debug

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
