# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= irq_fps_counter
GAME_TITLE	:= FPS counter
GAME_SUBTITLE	:= Interrupts

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
