# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Michele Di Giorgio, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= bios_rsa
GAME_TITLE	:= RSA example
GAME_SUBTITLE	:= BIOS

# Source code paths

BINDIRS		= data

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
