# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= keyboard_stdin
GAME_TITLE	:= stdin test
GAME_SUBTITLE	:= Keyboard

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
