# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= cothread_wait_for_signal
GAME_TITLE	:= Wait for signal
GAME_SUBTITLE	:= Cothread

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
