# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dyn_libs_basic_demo
GAME_TITLE	:= Basic demo
GAME_SUBTITLE	:= Dynamic libraries

# Source code paths

INCLUDEDIRS	:= source
NITROFSDIR	:= nitrofs

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
