# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= translucent_polygon
GAME_TITLE	:= Translucent 3D polygon

# Source code paths

GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
