# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_sys_swi_calls
GAME_TITLE	:= SWI calls test
GAME_SUBTITLE	:= Tests: System

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
