# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_fs_usage
GAME_TITLE	:= SD filesystem example
GAME_SUBTITLE	:= Tests: Filesystem

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
