# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= periph_backlight_level
GAME_TITLE	:= Backlight level
GAME_SUBTITLE	:= Peripherals

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
