# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= keyboard
GAME_TITLE	:= Keyboard example

# Source code paths

SOURCEDIRS	:= source

include ../../tests/Makefile.include
