# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= version_check_in_c
GAME_TITLE	:= Check version in C
GAME_SUBTITLE	:= Version

# Libraries

LIBDIRS		:= $(BLOCKSDS)/libs/libnds \
			   $(BLOCKSDS)/libs/version

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
