# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= fs_all_filesystems
GAME_TITLE	:= All filesystems
GAME_SUBTITLE	:= Filesystem

# Source code paths

NITROFSDIR	:= nitrofs

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
