# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024-2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= 3d_fog_over_2d
GAME_TITLE	:= Fog over 2D layers
GAME_SUBTITLE	:= 3D graphics

# Source code paths
# -----------------

BINDIRS		:= data
GFXDIRS		:= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
