# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= 3d_display_list_nitrofs
GAME_TITLE	:= Display list in NitroFS
GAME_SUBTITLE	:= 3D graphics

# Source code paths

NITROFSDIR		= nitrofs

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
