# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= libxm7_nitrofs_example

GAME_TITLE	:= LibXM7 + NitroFS example
GAME_SUBTITLE	:= how to use LibXM7
GAME_AUTHOR	:= (sverx, 2009-01-07)

# Source code paths

NITROFSDIR	:= nitrofs

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
