# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= periph_slot2
GAME_TITLE	:= Slot-2 peripheral example
GAME_SUBTITLE	:= Peripherals

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
