# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= cap_two_pass_3d
GAME_TITLE	:= Two pass 3D
GAME_SUBTITLE	:= Video capture

# Source code paths

GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
