# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= async_loading
GAME_TITLE	:= SD asynchronous loading

# Source code paths

NITROFATDIR	:= nitrofat

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
