# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= async_loading
GAME_TITLE	:= SD asynchronous loading

# Source code paths

SOURCEDIRS	:= source
NITROFATDIR	:= nitrofat

include ../../../tests/Makefile.include
