# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024-2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= fw_user_settings
GAME_TITLE	:= User settings
GAME_SUBTITLE	:= Firmware

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
