# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= ansi_console
GAME_TITLE	:= ANSI console

# Source code paths

SOURCEDIRS	:= source

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
