# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= time_rtc_get_set
GAME_TITLE	:= RTC get and set test
GAME_SUBTITLE	:= Time

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
