# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= cpp_example
GAME_TITLE	:= C++ example

# Source code paths

SOURCEDIRS	:= source

include ../../Makefile.include
