# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= fs_device_io_basic
GAME_TITLE	:= Basic device I/O example
GAME_SUBTITLE	:= Filesystem

# Source code paths

INCLUDEDIRS	:= source/lfs
NITROFSDIR	:= nitrofs

# Defines passed to all files

# Enable this to get debug prints from littlefs
#DEFINES	:= -DLFS_RAMBD_YES_TRACE -DLFS_YES_TRACE

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
