# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= photo_slideshow
GAME_TITLE	:= Photo Slideshow
GAME_SUBTITLE	:= Pics from your NAND!

# Source code paths

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
