# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= libxm7_example

GAME_TITLE	:= Basic example
GAME_SUBTITLE	:= LibXM7
GAME_AUTHOR	:= (sverx, 2009-01-07)

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
