# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= bios_decompress
GAME_TITLE	:= Decompress with BIOS
GAME_SUBTITLE	:= Compression

# Source code paths
# -----------------

BINDIRS		:= data

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
