# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= bg_display_control_steps
GAME_TITLE	:= DISPCNT slot steps
GAME_SUBTITLE	:= 2D graphics: BGs

# Source code paths
# -----------------

GFXDIRS		:= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
