// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Antonio Niño Díaz, 2026

// This example shows how to tell grit to use a predefined tile set as base when
// converting images. This can be useful in some cases:
//
// - If you know all the maps of one type (mountain, ocean, city) will share the
//   same tiles, and you want them to keep one specific order.
// - If you want to hardcode the index of some tiles so that you can get
//   information from the tile just based on the index. For example, all tiles
//   under index 20 could represent "floor", and all tiles over 50 could
//   represent "obstacle" in a platformer game.
// - If you want to animate the background by changing its tiles, you need to
//   know which tiles to modify.
//
// The hardest part is to create the image with the palette. grit needs to be
// able to load the colors in the right order. Use an image creation program
// that allows you to edit the palette if possible. If the colors of the tileset
// reference and the colors of the images don't match, it won't work.

#include <nds.h>

// They are generated by the `convert.sh` script.
#include "city.h"
#include "shared.h"

int main(int argc, char *argv[])
{
    videoSetMode(MODE_0_2D);
    videoSetModeSub(MODE_0_2D);

    vramSetPrimaryBanks(VRAM_A_MAIN_BG, VRAM_B_LCD, VRAM_C_SUB_BG, VRAM_D_LCD);

    // Setup the background

    int bg = bgInitHidden(2, BgType_Text8bpp, BgSize_T_512x512, 0, 1);

    memcpy(bgGetMapPtr(bg), cityMap, cityMapLen);
    memcpy(bgGetGfxPtr(bg), sharedTiles, sharedTilesLen);
    memcpy(BG_PALETTE, sharedPal, sharedPalLen);

    // Show it

    bgShow(bg);

    int x = 0, y = 0;

    while (1)
    {
        swiWaitForVBlank();

        bgSetScroll(bg, x, y);

        bgUpdate();

        scanKeys();

        u16 keys_held = keysHeld();

        if (keys_held & KEY_UP)
            y--;
        else if (keys_held & KEY_DOWN)
            y++;

        if (keys_held & KEY_LEFT)
            x--;
        else if (keys_held & KEY_RIGHT)
            x++;

        if (keys_held & KEY_START)
            break;
    }

    return 0;
}
