# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_graphics_texture_alloc
GAME_TITLE	:= Texure allocation tests
GAME_SUBTITLE	:= Tests: Graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
