# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= scfg_registers
GAME_TITLE	:= SCFG Registers

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
