# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= ipc_fifo_stress_test
GAME_TITLE	:= FIFO stress test
GAME_SUBTITLE	:= IPC

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
