# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= fifo_stress_test
GAME_TITLE	:= FIFO stress test

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
