# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= audio_capture

GAME_TITLE	:= Audio capture
GAME_SUBTITLE	:= Audio

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
