# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= nitrofat_and_fat
GAME_TITLE	:= NitroFAT+FAT example

# Source code paths

SOURCEDIRS	:= source
NITROFATDIR	:= nitrofat

include ../../tests/Makefile.include
