# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= bios_crc16
GAME_TITLE	:= CRC16 example
GAME_SUBTITLE	:= BIOS

# Source code paths

BINDIRS		= data

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
