# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= volumetric_shadow
GAME_TITLE	:= Volumetric Shadow

# Source code paths

BINDIRS		= data
GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
