# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= bg_regular_8bit_preexisting_tileset
GAME_TITLE	:= 8 bpp, preexisting tileset
GAME_SUBTITLE	:= 2D graphics: BGs

# Source code paths
# -----------------

SOURCEDIRS	:= source graphics_source
INCLUDEDIRS	:= source graphics_source

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
