# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= gl2d_2d_and_3d
GAME_TITLE	:= 2D and 3D
GAME_SUBTITLE	:= GL2D

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
