# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= 3d_texture_edge_modes
GAME_TITLE	:= Texture edge modes
GAME_SUBTITLE	:= 3D graphics

# Source code paths

GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
