# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_input_touch
GAME_TITLE	:= Touch input test
GAME_SUBTITLE	:= Tests: Input

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
