# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= fs_save_data
GAME_TITLE	:= Save data
GAME_SUBTITLE	:= Filesystem

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
