# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

BINDIRS		:= arm9/data

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7teak/Makefile.arm9
