# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dsp_dma_transfers
GAME_TITLE	:= DSP DMA transfers

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7teak/Makefile
