# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= nitrofat
GAME_TITLE	:= NitroFAT example

# Source code paths

SOURCEDIRS	:= source
NITROFATDIR	:= nitrofat

include ../../../tests/Makefile.include
