# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= audio_microphone
GAME_TITLE	:= Microphone demo
GAME_SUBTITLE	:= Audio

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
