# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024-2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= 3d_antialiasing_and_edge_marking
GAME_TITLE	:= Antialiasing & edge marking
GAME_SUBTITLE	:= 3D graphics

# Source code paths

BINDIRS		= data

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
