# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= mpu_regions
GAME_TITLE	:= MPU Regions

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
