# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= 3d_lighting_cube
GAME_TITLE	:= Lighting cube
GAME_SUBTITLE	:= 3D graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
