# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Michele Di Giorgio, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= maxmod_streaming
GAME_TITLE	:= Streaming
GAME_SUBTITLE	:= Maxmod

# Source code paths

NITROFSDIR  := nitrofs

# Libraries

LIBS		:= -lnds9 -lmm9
LIBDIRS		:= $(BLOCKSDS)/libs/maxmod

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
