# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024-2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= video_mode_fifo
GAME_TITLE	:= Video mode FIFO
GAME_SUBTITLE	:= 2D graphics

# Source code paths
# -----------------

GFXDIRS		:= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
