# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_sbrk
GAME_TITLE	:= Test sbrk behaviour
GAME_SUBTITLE	:= Tests: System

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
