# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dsp_dma_arm_to_dsp
GAME_TITLE	:= DMA ARM to DSP
GAME_SUBTITLE	:= DSP

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7teak/Makefile
