# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dsp_dma_dsp_to_arm
GAME_TITLE	:= DSP DMA DSP to ARM

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
