# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= ipc_pass_buffer_to_arm7
GAME_TITLE	:= ARM9 buffer to ARM7
GAME_SUBTITLE	:= IPC

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
