# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= pass_buffer_to_arm7
GAME_TITLE	:= Pass buffer from ARM9 to ARM7

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
