# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_sys_mpu_code_regions
GAME_TITLE	:= MPU Code Regions
GAME_SUBTITLE	:= Tests: System

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
