# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= box_test
GAME_TITLE	:= Box Test

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
