# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= libxm7_example

GAME_TITLE	:= LIBXM7 example
GAME_SUBTITLE	:= how to use LIBXM7
GAME_AUTHOR	:= (sverx, 2009-01-07)

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7/Makefile
