# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= input_keyboard
GAME_TITLE	:= Keyboard example
GAME_SUBTITLE	:= Input

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
