# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2026

BLOCKSDS	?= /opt/blocksds/core

NAME		:= xtensa

SOURCEDIRS	:= xtensa/source

include $(BLOCKSDS)/sys/default_makefiles/bin_xtensa/Makefile
