# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= thread_local_storage
GAME_TITLE	:= TLS example

# Source code paths

SOURCEDIRS	:= source

include ../Makefile.include
