# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= text_over_3d
GAME_TITLE	:= Text over 3D

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
