# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= bios_bit_unpack
GAME_TITLE	:= Bit unpacking with BIOS
GAME_SUBTITLE	:= Compression

# Source code paths
# -----------------

GFXDIRS		:= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
