# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= keyboard_stdin_read_blocking
GAME_TITLE	:= stdin read blocking
GAME_SUBTITLE	:= Keyboard

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
