# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024-2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= 3d_clear_plane_bitmap
GAME_TITLE	:= Clear plane bitmap
GAME_SUBTITLE	:= 3D graphics

# Source code paths

BINDIRS		= data
GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
