# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dsp_fifo_transfers
GAME_TITLE	:= DSP FIFO transfers

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9arm7teak/Makefile
