# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_sys_tcm_locations
GAME_TITLE	:= TCM locations
GAME_SUBTITLE	:= Tests: System

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
