# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024-2026

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= trig_functions_test
GAME_TITLE	:= Test for trig functions
GAME_SUBTITLE	:= Tests: Math

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
