# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= dsp_speakers_mic
GAME_TITLE	:= DSP speakers and mic

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9teak/Makefile
