# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_ipc_transfer_region
GAME_TITLE	:= Transfer region test
GAME_SUBTITLE	:= Tests: IPC

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
