# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_fs_short_name
GAME_TITLE	:= FAT_getShortNameFor() test
GAME_SUBTITLE	:= Tests: Filesystem

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
