# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

# User config

NAME		:= sync_to_vbl_cothread
GAME_TITLE	:= Sync to VBL cothread

# Source code paths

SOURCEDIRS	:= source

include ../../../tests/Makefile.include
