# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= sync_to_vbl_cothread
GAME_TITLE	:= Sync to VBL cothread

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
