# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= cothread_sync_to_vbl
GAME_TITLE	:= Sync to VBL
GAME_SUBTITLE	:= Cothread

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
