# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= nitrofat_and_fat
GAME_TITLE	:= NitroFAT+FAT example

# Source code paths

SOURCEDIRS	:= source
NITROFATDIR	:= nitrofat

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
