# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= test_cothread_wait_irq
GAME_TITLE	:= Wait for interrupt
GAME_SUBTITLE	:= Tests: Cothread

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
