# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2025

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= 3d_modulation_vs_decal
GAME_TITLE	:= Modulation vs decal
GAME_SUBTITLE	:= 3D graphics

# Source code paths

BINDIRS		= data
GFXDIRS		= graphics

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
