# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= touch_input
GAME_TITLE	:= Touch input demo

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
