// SPDX-License-Identifier: CC0-1.0
//
// SPDX-FileContributor: Antonio Niño Díaz, 2024-2025

// This example enables alpha test with GL_ALPHA_TEST and then it lets the user
// change the alpha threshold with glAlphaFunc(). Only pixels with a bigger
// alpha value get drawn. A threshold of 0 will allow all pixels to be drawn, a
// threshold of 31 will prevent everything from being drawn (even opaque
// polygons!).

#include <stdio.h>

#include <nds.h>

// Header autogenerated for each PNG file inside GFXDIRS in the Makefile
#include "neon.h"
#include "neon2.h"

__attribute__((noreturn)) void wait_forever(void)
{
    printf("Press START to exit.");

    while (1)
    {
        swiWaitForVBlank();

        scanKeys();
        if (keysHeld() & KEY_START)
            exit(1);
    }
}

int main(int argc, char **argv)
{
    int textureID[2];

    // Setup sub screen for the text console
    consoleDemoInit();

    videoSetMode(MODE_0_3D);

    glInit();

    glEnable(GL_TEXTURE_2D);
    glEnable(GL_ANTIALIAS);
    glEnable(GL_BLEND);
    glEnable(GL_ALPHA_TEST); // Enable alpha test

    // The background must be fully opaque and have a unique polygon ID
    // (different from the polygons that are going to be drawn) so that
    // antialias works.
    glClearColor(0, 0, 0, 31);
    glClearPolyID(63);

    glClearDepth(0x7FFF);

    glViewport(0, 0, 255, 191);

    // Setup some VRAM as memory for textures and texture palettes
    vramSetBankA(VRAM_A_TEXTURE);
    vramSetBankF(VRAM_F_TEX_PALETTE);

    // Load textures
    glGenTextures(2, &textureID[0]);

    glBindTexture(0, textureID[0]);
    if (glTexImage2D(0, 0, GL_RGBA, 128, 128, 0, TEXGEN_TEXCOORD, neonBitmap) == 0)
    {
        printf("Failed to load texture 1\n");
        wait_forever();
    }

    glBindTexture(0, textureID[1]);
    if (glTexImage2D(0, 0, GL_RGB8_A5, 128, 128, 0, TEXGEN_TEXCOORD, neon2Bitmap) == 0)
    {
        printf("Failed to load texture 2\n");
        wait_forever();
    }
    if (glColorTableEXT(0, 0, 8, 0, 0, neon2Pal) == 0)
    {
        printf("Failed to load palette 2\n");
        wait_forever();
    }

    // Setup matrices
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    gluPerspective(70, 256.0 / 192.0, 0.1, 40);

    gluLookAt(0.0, 0.0, 2.0,  // Position
              0.0, 0.0, 0.0,  // Look at
              0.0, 1.0, 0.0); // Up

    int angle_x = 0;
    int angle_z = 0;

    int alpha_threshold = 15;

    while (1)
    {
        // Synchronize game loop to the screen refresh
        swiWaitForVBlank();

        // Print some text in the demo console
        // -----------------------------------

        consoleClear();

        // Print some controls
        printf("PAD:    Rotate triangle\n");
        printf("L/R:    Set alpha threshold: %2d\n", alpha_threshold);
        printf("\n");
        printf("START:  Exit to loader\n");

        // Handle user input
        // -----------------

        scanKeys();

        uint16_t keys = keysHeld();

        if (keys & KEY_LEFT)
            angle_z += 3;
        if (keys & KEY_RIGHT)
            angle_z -= 3;

        if (keys & KEY_UP)
            angle_x += 3;
        if (keys & KEY_DOWN)
            angle_x -= 3;

        if (keys & KEY_START)
            break;

        uint16_t keys_down = keysDown();
        if ((keys_down & KEY_L) && (alpha_threshold > 0))
            alpha_threshold--;
        else if ((keys_down & KEY_R) && (alpha_threshold < 31))
            alpha_threshold++;

        // Render 3D scene
        // ---------------

        glAlphaFunc(alpha_threshold);

        glMatrixMode(GL_MODELVIEW);

        glPushMatrix();

        glPolyFmt(POLY_ALPHA(31) | POLY_CULL_NONE);

        glBindTexture(0, textureID[0]);

        glColor3f(1, 1, 1);

        glBegin(GL_QUADS);

            glTexCoord2t16(0, inttot16(128));
            glVertex3v16(floattov16(-1), floattov16(-1), floattov16(-0.2));

            glTexCoord2t16(inttot16(128), inttot16(128));
            glVertex3v16(floattov16(1), floattov16(-1), floattov16(-0.2));

            glTexCoord2t16(inttot16(128), 0);
            glVertex3v16(floattov16(1), floattov16(1), floattov16(-0.2));

            glTexCoord2t16(0, 0);
            glVertex3v16(floattov16(-1), floattov16(1), floattov16(-0.2));

        glEnd();

        glRotateZ(angle_z);
        glRotateX(angle_x);

        glBindTexture(0, textureID[1]);

        glColor3f(1, 1, 1);

        glBegin(GL_QUADS);

            glTexCoord2t16(0, inttot16(128));
            glVertex3v16(floattov16(-1), floattov16(-1), 0);

            glTexCoord2t16(inttot16(128),inttot16(128));
            glVertex3v16(floattov16(1), floattov16(-1), 0);

            glTexCoord2t16(inttot16(128), 0);
            glVertex3v16(floattov16(1), floattov16(1), 0);

            glTexCoord2t16(0, 0);
            glVertex3v16(floattov16(-1), floattov16(1), 0);

        glEnd();

        glPopMatrix(1);

        glFlush(0);
    }

    glDeleteTextures(2, &textureID[0]);

    return 0;
}
