# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= data_cache_ops
GAME_TITLE	:= Data cache ops test

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
