# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023-2024

BLOCKSDS	?= /opt/blocksds/core

# User config

NAME		:= tests_cache_dc_ops
GAME_TITLE	:= Data cache ops test
GAME_SUBTITLE	:= Tests: Cache

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
